apiVersion: v2
name: homebridge 
description: https://github.com/homebridge/homebridge
type: application
version: 1.0.57
# renovate: datasource=docker depName=ghcr.io/homebridge/homebridge versioning=loose
appVersion: "2026-01-24"
