apiVersion: v2
name: homebridge 
description: https://github.com/homebridge/homebridge
type: application
version: 1.0.48
# renovate: datasource=docker depName=ghcr.io/homebridge/homebridge versioning=loose
appVersion: "2025-12-16"
