image:
  repository: "nodered/node-red"
  tag: "4.1.5-20@sha256:7dfe40efdd7b9f21916f083802bfe60a762bc020969d95553ffa020c97a72eb9"
nfs:
  server: 192.168.1.4
  path: "/nfs/node-red"
env:
  - name: NRCHKB_EXPERIMENTAL
    value: "true"
