image:
  repository: ghcr.io/koenkk/zigbee2mqtt
  tag: 2.8.0@sha256:89cf02f379aa743a68494388e3a26fba7b8c9101f8b452038cc07aeff3fc983c
port: 8080
timezone: Europe/Berlin
nfs:
  server: 192.168.1.4
  path: "/nfs/zigbee2mqtt"
